question_data = [
    {
        "difficulty": "easy",
        "question": "How long is an IPv6 address?",
        "correct_answer": "128 bits",
        "options": ["32 bits", "64 bits", "128 bytes", "128 bits"],
    },
    {
        "difficulty": "easy",
        "question": "The C programming language was created by this American computer scientist. ",
        "correct_answer": "Dennis Ritchie",
        "options": [
            "Dennis Ritchie",
            "Tim Berners Lee",
            "al-Khw\u0101rizm\u012b",
            "Willis Ware",
        ],
    },
    {
        "difficulty": "easy",
        "question": "On Twitter, what was the original character limit for a Tweet?",
        "correct_answer": "140",
        "options": ["140", "120", "160", "100"],
    },
    {
        "difficulty": "easy",
        "question": "What does CPU stand for?",
        "correct_answer": "Central Processing Unit",
        "options": [
            "Central Process Unit",
            "Central Processing Unit",
            "Computer Personal Unit",
            "Central Processor Unit",
        ],
    },
    {
        "difficulty": "easy",
        "question": "Which language is primarily used for Android development?",
        "correct_answer": "Kotlin",
        "options": ["Swift", "JavaScript", "Kotlin", "C#"],
    },
    {
        "difficulty": "easy",
        "question": "What programming language was GitHub written in?",
        "correct_answer": "Ruby",
        "options": [
            "JavaScript",
            "Python",
            "Lua",
            "Ruby",
        ],
    },
    {
        "difficulty": "easy",
        "question": "Who is known as the father of the computer?",
        "correct_answer": "Charles Babbage",
        "options": [
            "Alan Turing",
            "Charles Babbage",
            "Tim Berners-Lee",
            "John von Neumann",
        ],
    },
    {
        "difficulty": "easy",
        "question": "What is the most preferred image format used for logos in the Wikimedia database?",
        "correct_answer": ".svg",
        "options": [".svg", ".png", ".jpeg", ".gif"],
    },
    {
        "difficulty": "easy",
        "question": "Which company developed the Windows operating system?",
        "correct_answer": "Microsoft",
        "options": ["Apple", "IBM", "Microsoft", "Google"],
    },
    {
        "difficulty": "easy",
        "question": "Which SQL keyword is used to fetch data from a database?",
        "correct_answer": "SELECT",
        "options": ["INDEX", "SELECT", "VALUES", "EXEC"],
    },
    {
        "difficulty": "medium",
        "question": "Which of these is a Python web framework?",
        "correct_answer": "Django",
        "options": ["Laravel", "Flask", "Django", "Spring"],
    },
    {
        "difficulty": "medium",
        "question": ".at is the top-level domain for what country?",
        "correct_answer": "Austria",
        "options": ["Argentina", "Australia", "Angola", "Austria"],
    },
    {
        "difficulty": "medium",
        "question": "Whistler was the codename of this Microsoft Operating System.",
        "correct_answer": "Windows XP",
        "options": [
            "Windows 2000",
            "Windows 7",
            "Windows 95",
            "Windows XP",
        ],
    },
    {
        "difficulty": "medium",
        "question": "How many bits make up the significand portion of a single precision floating point number?",
        "correct_answer": "23",
        "options": ["23", "8", "53", "15"],
    },
    {
        "difficulty": "medium",
        "question": "What does the acronym CDN stand for in terms of networking?",
        "correct_answer": "Content Delivery Network",
        "options": [
            "Content Distribution Network",
            "Computational Data Network",
            "Content Delivery Network",
            "Compressed Data Network",
        ],
    },
    {
        "difficulty": "medium",
        "question": "What does the &#039;S&#039; in the RSA encryption algorithm stand for?",
        "correct_answer": "Shamir",
        "options": ["Shamir", "Secure", "Schottky", "Stable"],
    },
    {
        "difficulty": "medium",
        "question": "While Apple was formed in California, in which western state was Microsoft founded?",
        "correct_answer": "New Mexico",
        "options": ["Washington", "New Mexico", "Colorado", "Arizona"],
    },
    {
        "difficulty": "medium",
        "question": "Which protocol is used to securely transfer files over the internet?",
        "correct_answer": "SFTP",
        "options": ["SFTP", "HTTP", "FTP", "SMTP"],
    },
    {
        "difficulty": "medium",
        "question": "Which of the following is a NoSQL database?",
        "correct_answer": "MongoDB",
        "options": ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
    },
    {
        "difficulty": "medium",
        "question": "What does the term MIME stand for, in regards to computing?",
        "correct_answer": "Multipurpose Internet Mail Extensions",
        "options": [
            "Multipurpose Internet Mail Extensions",
            "Mail Internet Mail Exchange",
            "Multipurpose Interleave Mail Exchange",
            "Mail Interleave Method Exchange",
        ],
    },
    {
        "difficulty": "hard",
        "question": "Released in 2001, the first edition of Apple's Mac OS X operating system (version 10.0) was given what animal code name?",
        "correct_answer": "Cheetah",
        "options": ["Cheetah", "Puma", "Tiger", "Leopard"],
    },
    {
        "difficulty": "hard",
        "question": "Which kind of algorithm is Ron Rivest not famous for creating?",
        "correct_answer": "Secret sharing scheme",
        "options": [
            "Hashing algorithm",
            "Secret sharing scheme",
            "Asymmetric encryption",
            "Stream cipher",
        ],
    },
    {
        "difficulty": "hard",
        "question": "Which RAID array type is associated with data mirroring?",
        "correct_answer": "RAID 1",
        "options": ["RAID 1", "RAID 0", "RAID 10", "RAID 5"],
    },
    {
        "difficulty": "hard",
        "question": "What port does HTTP run on?",
        "correct_answer": "80",
        "options": ["53", "443", "80", "23"],
    },
    {
        "difficulty": "hard",
        "question": "What was the name of the security vulnerability found in Bash in 2014?",
        "correct_answer": "Shellshock",
        "options": ["Heartbleed", "Bashbug", "Stagefright", "Shellshock"],
    },
    {
        "difficulty": "hard",
        "question": "Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?",
        "correct_answer": "Heartbleed",
        "options": ["Shellshock", "Corrupted Blood", "Heartbleed", "Shellscript"],
    },
    {
        "difficulty": "hard",
        "question": "Which of the following is the oldest of these computers by release date?",
        "correct_answer": "TRS-80",
        "options": ["Commodore 64", "ZX Spectrum", "TRS-80", "Apple 3"],
    },
    {
        "difficulty": "hard",
        "question": "What major programming language does Unreal Engine 4 use?",
        "correct_answer": "C++",
        "options": ["Assembly", "C++", "C#", "ECMAScript"],
    },
    {
        "difficulty": "hard",
        "question": "What is the name given to layer 4 of the Open Systems Interconnection (ISO) model?",
        "correct_answer": "Transport",
        "options": ["Transport", "Session", "Data link", "Network"],
    },
    {
        "difficulty": "hard",
        "question": "Which sorting algorithm has the best average-case time complexity?",
        "correct_answer": "Merge Sort",
        "options": ["Selection Sort", "Bubble Sort", "Merge Sort", "Insertion Sort"],
    },
]
